# Generated by Django 4.2.6 on 2023-10-17 15:22

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddings",
            name="text_vectors",
            field=pgvector.django.VectorField(null=True, dimensions=1536),
        ),
    ]
